apiVersion: v1
kind: Service
metadata:
  name: cio-prom
  labels:
    name: cio-prom
spec:
  ports:
  - port: 16995
  selector:
    app: cio-prom

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cio-prom
spec:
  selector:
    matchLabels:
      app: cio-prom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cio-prom
    spec:
      hostNetwork: true
      containers:
      - image: storidge/cio-prom:dev
        name: cio-prom
        ports:
        - containerPort: 16995
          name: cio-prom
        imagePullPolicy: Always
