apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: frontend
spec:
  containers:
   - name: nginx-server
     image: nginx
     ports:
       - containerPort: 80
         name: "http-server"
     volumeMounts:
       - name: nginx-vol
         mountPath: /usr/share/nginx/html
  volumes:
   - name: nginx-vol
     persistentVolumeClaim:
       claimName: nginx-pvc
       readOnly: false
